name: Deploy dev -> main:/beta

on:
  push:
    branches: [ dev ]
  workflow_dispatch: {}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install bundler & dependencies
        run: |
          gem install bundler
          bundle config set --local deployment 'true'
          bundle install --jobs 4 --retry 3

      - name: Build site (Jekyll)
        run: bundle exec jekyll build --destination _site

      - name: Remove CNAME from build (prevent overriding custom domain)
        run: rm -f _site/CNAME || true

      - name: Checkout main into separate folder
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          token: ${{ secrets.GITHUB_TOKEN }}
          path: main-worktree

      - name: Copy built site into main-worktree/beta
        run: |
          rm -rf main-worktree/beta || true
          mkdir -p main-worktree/beta
          cp -a _site/. main-worktree/beta/

      - name: Commit & push beta content to main
        run: |
          cd main-worktree
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A beta
          git commit -m "Deploy dev -> beta: $GITHUB_SHA" || echo "No changes to commit"
          # ensure push uses token auth (works around some permission/remote issues)
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
